name: Release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  create:
    tags:
      - v*

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        target: [
            i686-unknown-linux-gnu,
            x86_64-unknown-linux-gnu,
        ]
    steps:
      - name: Install required libraries
        run: |
          sudo apt-get update
          sudo apt-get install liblzma-dev -y
      - name: Install 32-bit libraries
        if: matrix.target == 'i686-unknown-linux-gnu'
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install gcc-multilib zlib1g-dev:i386 liblzma-dev:i386 libgcc1:i386 -y
      - name: Setup rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable-${{ matrix.target }}
          target: ${{ matrix.target }}
          override: true
          default: true
      - name: Install rpm and deb packaging tools
        run: cargo install cargo-rpm cargo-deb --no-default-features

      - uses: actions/checkout@v2
      - name: Build generic Linux binary
        run: cargo build --verbose --release
      - name: Package Linux .deb
        run: cargo deb
      - name: Package Linux .rpm
        run: cargo rpm build -v --target ${{ matrix.target }}

      - name: Run tests
        run: cargo test --verbose
      - name: Archive build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: linux-artifacts
          retention-days: 5
          path: |
            target/debian
            target/*/release/rpmbuild/RPMS
  build-windows:
    runs-on: windows-2016
    strategy:
      matrix:
        target: [
          i686-pc-windows-msvc,
          x86_64-pc-windows-msvc,
        ]
    steps:
      - name: Setup rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable-${{ matrix.target }}
          target: ${{ matrix.target }}
          override: true
          default: true
      - name: Install wix packager for cargo
        run: cargo install cargo-wix

      - uses: actions/checkout@v2
      - name: Build Windows binary
        run: cargo build --verbose --release
      - name: Build Windows installer
        run: cargo wix --verbose --nocapture

      - name: Run tests
        run: cargo test --verbose
      - name: Archive build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: windows-artifacts
          retention-days: 5
          path: |
            target/wix
  build-mac:
    runs-on: macos-latest
    strategy:
      matrix:
        target: [
            aarch64-apple-darwin,
            x86_64-apple-darwin,
        ]
    steps:
      - name: Setup rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
          default: true
      - uses: actions/checkout@v2
      - name: Build Mac binary
        run: cargo build --verbose --release
      - name: Run tests
        run: cargo test --verbose
      - name: Rename binaries
        run: mv target/release/firefox_profile_switcher_connector target/release/mac-${{ matrix.target }}
      - name: Archive build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: mac-artifacts
          retention-days: 5
          path: |
            target/release/mac-${{ matrix.target }}
            manifest/manifest-mac.json
  release:
    needs: [build-linux, build-windows]
    runs-on: ubuntu-latest
    steps:
      - name: Install utils
        run: |
          sudo apt-get update
          sudo apt-get install -y rename
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v2
      - name: Rename artifacts
        run: |
          pushd linux-artifacts
          find . -mindepth 2 -type f -exec mv -t . -n '{}' + # Flatten directory
          rename -E 's/^ff-pswitch-connector_.+?_(.+\.deb)$/linux-$1/' *.deb
          rename -E 's/^ff-pswitch-connector-.+\.(.+\.rpm)$/linux-$1/' *.rpm
          popd
          pushd windows-artifacts
          find . -mindepth 2 -type f -exec mv -t . -n '{}' + # Flatten directory
          rename -E 's/^firefox_profile_switcher_connector-.+?-(.+msi)$/windows-$1/' *.msi
          popd
          pushd mac-artifacts
          find . -mindepth 2 -type f -exec mv -t . -n '{}' + # Flatten directory
          rename -E 's/^mac-(.+?)-apple-darwin$/mac-$1/' mac-*
          mv manifest-mac.json mac-manifest.json
          popd
          rename -E 's/amd64/x86_64/' linux-artifacts/* windows-artifacts/* mac-artifacts/*
          rename -E 's/x86_64/x64/' linux-artifacts/* windows-artifacts/* mac-artifacts/*
          rename -E 's/i386/i686/' linux-artifacts/* windows-artifacts/* mac-artifacts/*
          rename -E 's/i686/x86/' linux-artifacts/* windows-artifacts/* mac-artifacts/*
      - name: Archive build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: release-artifacts
          retention-days: 5
          path: |
            linux-artifacts
            windows-artifacts
            mac-artifacts
      - name: Changelog
        id: Changelog
        uses: metcalfc/changelog-generator@v1.0.0
        if: startsWith(github.ref, 'refs/tags/')
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body: |
            ${{ steps.Changelog.outputs.changelog }}
          draft: false
          prerelease: false
          files: |
            linux-artifacts/*.deb
            linux-artifacts/*.rpm
            windows-artifacts/*.msi
            mac-artifacts/mac-*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
